# Default Compose config: runs GHC with SQLite backend and cronjobs
version: "3"

services:
  geohealthcheck:
    image: geopython/geohealthcheck:latest
    ports:
      - 8083:80
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB

  geohealthcheck-cron-hourly:
    image: geopython/geohealthcheck:latest
    depends_on:
      - geohealthcheck

    # Override settings to enable email notifications
#    environment:
#      LC_ALL: "nl_NL.UTF-8"
#      LANG: "nl_NL.UTF-8"
#      LANGUAGE: "nl_NL.UTF-8"
#      GHC_NOTIFICATIONS: 'true'
#      GHC_NOTIFICATIONS_VERBOSITY: 'true'
#      GHC_ADMIN_EMAIL: 'us@gmail.com'
#      GHC_NOTIFICATIONS_EMAIL: 'us@gmail.com,them@domain.com'
#      GHC_SMTP_SERVER: 'smtp.gmail.com'
#      GHC_SMTP_PORT: 587
#      GHC_SMTP_TLS: 'true'
#      GHC_SMTP_SSL: 'false'
#      GHC_SMTP_USERNAME: 'us@gmail.com'
#      GHC_SMTP_PASSWORD: 'the_passw'

    entrypoint:
      - bash
      - /cron-jobs-hourly.sh
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB
    labels:
      io.ghc-cron-hourly: 'true'

  geohealthcheck-cron-daily:
    image: geopython/geohealthcheck:latest
    depends_on:
      - geohealthcheck
    entrypoint:
      - bash
      - /cron-jobs-daily.sh
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB
    labels:
      io.ghc-cron-daily: 'true'

  jobber:
    image: blacklabelops/jobber:docker.v1.1
    depends_on:
      - geohealthcheck-cron-hourly
      - geohealthcheck-cron-daily
    environment:
      JOB_NAME1: ghc-cron-hourly
      JOB_COMMAND1: docker start $$(docker ps -a -f label=io.ghc-cron-hourly=true --format="{{.ID}}")
      JOB_TIME1: 0 0 *
      JOB_NAME2: ghc-cron-daily
      JOB_COMMAND2: docker start $$(docker ps -a -f label=io.ghc-cron-daily=true --format="{{.ID}}")
      JOB_TIME2: 0 45 0 *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# docker-compose v2+ needs separate volumes section
volumes:
  ghc_sqlitedb:
